### ISSUE TITLE
"Show outline as text" option doesn't reflect the current state of the View

### ISSUE THREAD

**Issue by therden** [dagraham/etm-tk#27]
(In version 3.0.37)   
 
The menu option **View | Show Outline as Text** *generates output which doesn't match the state of the outline in the View pane.*  

Instead, it follows the overall "Outline depth" setting (either the last setting selected during the current ETM session or the Default value.)

Fix may require **"walking the entire tree and checking the state of each node."**

**Comment by dagraham** [comment]
I'm not going to be able to implement this. Outline as Text will continue to mirror the outline depth setting.
