### ISSUE TITLE
csv export of custom report does not work and crashes etm

### ISSUE THREAD

**Issue by aeromorrison** [dagraham/etm-tk#32]
The screenshot below shows what I get when I try to export a csv file. The dialog basically does nothing. I'm actually not sure if this is supposed to be a file dialog or what? Anything I click on does nothing. If I cancel the dialog, then etm crashes instantly.
I tried turning on the debug dialogs, but there wasn't anything useful written to the output (although etm did not crash).

![csv_export_dialog](https://cloud.githubusercontent.com/assets/7440842/5952126/19b511e4-a73f-11e4-8964-713d98f113d0.png)

**Comment by aeromorrison** [comment]
I've looked at some of the code. The issue is that that FileChoice class expects to already see a file that can be selected from. It seems to default to the load path for etm as the directory. When there isn't an existing csv file, it returns the directory which the subsequent CSV.writer command crashes on because it isn't a file.

If I put an empty csv file in the directory, then I am able to get an export without an error.

I guess I was expecting to see a file dialog where I could select where I want to put the file and the file name. Or, if it could default to an export directory or something, that would work as well.

**Comment by dagraham** [comment]
Would you try an experiment for me? In view.py line 3982 would you change new=False to new=True and see if it addresses this issue?

Thanks,
Dan

**Comment by aeromorrison** [comment]
Sorry for the delay in testing this. It definitely improves the behavior. I get an extra dialog box where I can enter a file name. I am still limited to putting the file within a sub-directory of my startup user profile directory tree (which is not where I store my data files). It's definitely less confusing behavior.

**Comment by dagraham** [comment]
I'll add "exportdir" to the options for the config file so you can 
specify the location you like.

-Dan

**Comment by dagraham** [comment]
I've added exportdir and changed the documentation. This will be available in the next release.
