### ISSUE TITLE
Date Calculator and documentation

### ISSUE THREAD

**Issue by therden** [dagraham/etm-tk#35]
The Date Calculator In the current version of ETM isn't able to process some of the examples of fuzzy date parsing provided in the Users Manual.  Attempting to calculate the value of +1/1, -1/1, or +2/15 results in a "can't parse" error message.

Also:  the Users Manual indicates that F5 should raise the Date Calculator, but the current keyboard shortcut is Shift-D.

**Comment by dagraham** [comment]
Yes, the short is Shift-D. This is listed correctly in keyboard 
shortcuts but not in a couple of places elsewhere in the manual. It 
would be helpful if you could point to the exact locations when you 
identify typos or, even better, you could correct the documentation 
yourself on the wiki.

It's true that the date calculator will not process relative dates that 
use either plus or minus prefixes, such as the examples you give, but it 
will accept other fuzzy dates  such as "now + 3w".

-Dan

**Comment by therden** [comment]
I'd actually forgotten about the wiki.  (After a quick trial last year, I went back to using the HTML version of the Users Manual -- it was easier to access and search and, I felt, more authoritative.)

As per your request, I've edited the wiki, replacing references to **F5** with **Shift-D**.

How would you want the *"Fuzzy Dates"* material to be corrected?  

Is the Date Calculator's lack of support for ```+1/1``` and ```-2/15``` -style a bug which will be corrected?  If not, then should the examples which don't work in the Date Calculator simply be deleted?  Or should the section be reorganized and written so as to identify which examples work in conjunction with **Ctrl-J** and as **@s** values but do not with the Date Calculator?

**Comment by dagraham** [comment]
The problem with the use of + and - in relative dates is that they conflict with the use of + and - in adding and subtracting dates in the date calculator.  I have no plans or idea of how to fix this.

**Comment by therden** [comment]
Understood; thank you Dan.
