### ISSUE TITLE
When a Someday/Maybe item is selected, the user can't create a New item.

### ISSUE THREAD

**Issue by therden** [dagraham/etm-tk#36]
When a Someday (prefixed with a "? ") item is selected, the user can't create a New item.

Whether she presses the N key, or select File | New | Item from the menu, nothing happens.

**Comment by dagraham** [comment]
I can't duplicate this on my mac. Is any error output written to the 
terminal?

**Comment by therden** [comment]
Here you go:
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "C:\Users\50a597\MyApps\Anaconda\lib\tkinter\__init__.py", line 1487, in __call__
>     return self.func(*args)
>   File "C:\Users\50a597\MyApps\etmtk-latest\etmTk\view.py", line 946, in <lambda>
>     self.tree.bind(c, lambda e: self.after(AFTER, cmd(e)))
>   File "C:\Users\50a597\MyApps\etmtk-latest\etmTk\view.py", line 216, in <lambda>
>     self.bindTop(c, lambda e: self.after(AFTER, self.newItem(e)))
>   File "C:\Users\50a597\MyApps\etmtk-latest\etmTk\view.py", line 1192, in newItem
>     changed = SimpleEditor(parent=self, master=master, start=text, options=loop.options).changed
> UnboundLocalError: local variable 'text' referenced before assignment

Thank you for checking this out.

**Comment by dagraham** [comment]
I think this is fixed in the latest commit.
