### ISSUE TITLE
Items w/out attributes displaying in branch named " " or "" rather than the expected "~~~"

### ISSUE THREAD

**Issue by therden** [dagraham/etm-tk#37]
In Agenda View items without an assigned Context attribute used to appear at the bottom of the Next section in branch labeled "~\~~".  Similarly, items lacking a Keyword assignment would appear in "~\~~" section at the bottom of the Keyword view.  The same behavior occurred in the Tag View.

In the current master build, items without attributes (for example, no assigned Context, Keyword, or Tag) are being displayed in a branch displayed at the top with an invisible attribute.  (I can't tell if it is an empty string or a string of one or more spaces.)

**Comment by dagraham** [comment]
It's an empty string to reflect the fact that none was entered. A 
consequence, as you note, is that items missing a context (or whatever) 
git listed first. What would you recommend?

**Comment by therden** [comment]
I agree that including items which lack a given attribute in a View or Section which focuses on that attribute is a Good Thing; but I think it is useful primarily when one is in _Review_ mode -- the time you'll ask yourself "Should any items which lack a given attribute (Context, Keyword, or Tag) be assigned one?"

When you want to plow through your _Next Actions_, on the other hand, having the attribute-lacking items at the top of the list will be distracting.  For that reason alone, I recommend returning to the previous practice of assigning either __~\~~__ or the "more informative, but still bottom-sorting" __{None}__ to items which haven't been assigned a value for a particular attribute class.

**Comment by dagraham** [comment]
Thanks - I'm convinced.

-Dan

**Comment by dagraham** [comment]
Corrected - now displays "~ None ~".
