### ISSUE TITLE
Feature request: Keybinding

### ISSUE THREAD

**Issue by stef204** [dagraham/etm-tk#41]
**Keybinding for `<Enter>` key in Number Pad.**

A keybinding for `<Enter>` on the numpad would be useful.  As it stands, it seems that only pressing `<Enter>` on main keyboard works to "OK" Alert Dialogs.

For users entering numbers on numpad, pressing `<Enter>` on numpad is ignored.

My keycodes (under X, using xev):
36 Return
104 KP_Enter

36 is bound but 104 is not.

**Comment by dagraham** [comment]
Stef,
My keyboard doesn't have a numpad. Could you check the current github version for me and see if KP_Enter works? Thanks 
-Dan

**Comment by dagraham** [comment]
This key binding will be provided in 3.2.6.

**Comment by stef204** [comment]
The keybinding now works, with version 3.2.6. Thank you.
