### ISSUE TITLE
@o values disallowed for Note items 

### ISSUE THREAD

**Issue by therden** [dagraham/etm-tk#43]
I'm uncertain whether this post represents a bug report or a feature request...

ETM allows Note items to be assigned @s and @r key/value pairs, but not @o values.  Can this limitation be removed?

(Notes can have alerts, and I'm ~~abusing~~ using Notes with p;-type alerts to kick off certain processes automatically and recurringly, without these items cluttering up Next/Agenda view.  As with other recurring items, I'd like to be able to control how ETM handles "overdue" recurrences of these Notes too, so that ones from past dates/times don't clutter up Week/Month view either.)

**Comment by dagraham** [comment]
The mistake is allowing @r entries in notes. You wanted tasks to be events and now you want notes to be tasks. Sorry, I won’t have time for quite a while to worry about this - classes start Tuesday.

On Aug 19, 2015, at 4:43 PM, therden <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm uncertain whether this post represents a bug report or a feature request...

ETM allows Note items to be assigned @s<https://github.com/s> and @r<https://github.com/r> key/value pairs, but not @o<https://github.com/o> values. Can this limitation be removed?

(Notes can have alerts, and I'm abusing using Notes with p;-type alerts to kick off certain processes automatically and recurringly, without these items cluttering up Next/Agenda view. As with other recurring items, I'd like to be able to control how ETM handles "overdue" recurrences of these Notes too, so that ones from past dates/times don't clutter up Week/Month view either.)

**Comment by dagraham** [comment]
It seems to me that cron would be a much better solution to your "start processes without clutter" objective than etm.

**Comment by therden** [comment]
My employer is a Windows-only shop, and the Windows equivalent (?) of cron
-- Task Scheduler -- requires Administrator rights to use. Unfortunately,
mine is not an Admin account.

Using etm Task items for this purpose worked pretty well; the chief
drawback was that the items occupied precious space in Next/Agenda view.
Then I reviewed the options you've made available, and discovered that
etm's Note items worked even better -- until I stumbled across the lack of
support for @o.

I accept that you aren't going to change that.  But *please* don't remove
the support for @r and @a attributes in Notes items.

Thank you for your consideration,
-Thomas

**Comment by dagraham** [comment]
No, I misspoke. I had forgotten that the icalendar specs provide for rrules in journal entries (etm notes) and I try to make etm as consistent as possible.

When I have time, I might be able to find a way to specify tasks that should not appear in now/next.

I’m sorry to hear about your being stuck with Windoz - it happened to me once.

-Dan


On Aug 20, 2015, at 12:12 AM, therden <notifications@github.com<mailto:notifications@github.com>> wrote:

My employer is a Windows-only shop, and the Windows equivalent (?) of cron
-- Task Scheduler -- requires Administrator rights to use. Unfortunately,
mine is not an Admin account.

Using etm Task items for this purpose worked pretty well; the chief
drawback was that the items occupied precious space in Next/Agenda view.
Then I reviewed the options you've made available, and discovered that
etm's Note items worked even better -- until I stumbled across the lack of
support for @o.

I accept that you aren't going to change that. But *please* don't remove
the support for @r and @a attributes in Notes items.

Thank you for your consideration,
-Thomas

**Comment by dagraham** [comment]
If you could limit where a task would appear, where would you want it to be displayed?

**Comment by dagraham** [comment]
Still thinking. What if there were a new type of task with _ (underscore) as the type character? This would be identical to a normal task save for the fact that it would only appear in the path view.

**Comment by therden** [comment]
I really appreciate your consideration.  Honestly,  Note items are nearly
perfect for my purpose - the only hitch is the lack of @o support. If it
would be a headache to add that, I can live with it.
Take care,
-Thomas

**Comment by dagraham** [comment]
What I proposed would be an order of magnitude easier than modifying a note to behave is some, but not all, respects like a task.

On Aug 20, 2015, at 8:23 AM, therden <notifications@github.com<mailto:notifications@github.com>> wrote:

I really appreciate your consideration. Honestly, Note items are nearly
perfect for my purpose - the only hitch is the lack of @o support. If it
would be a headache to add that, I can live with it.
Take care,
-Thomas

**Comment by dagraham** [comment]
Ok, here is the latest. The branch “noshow” on github adds the possibility of using “@n” with itemtype “-“  (tasks). @n stands for “do not show" and takes a list of one letter views from a) agenda, d) day (week and month), t) tag and k) keyword. For example, “@n a, d” would hide the task from agenda, week and month views but would allow it to be shown in tag and keyword views. It is not possible to prevent it being shown in path view. Thus “@n a, d, k, t” would hide it from all views except path. I’m thinking that this would give you the behavior you want without resorting to mis-using notes. Let me know.

**Comment by therden** [comment]
Hi Dan,

Sorry for the delayed response; I was occupied all day taking one of my
kids to visit a college campus a few hours away.

Your proposed new @n attribute sounds like it'll work great for my purpose
of using etm as a kind of "poor man's cron."

Thank you very much for taking the time to think about how to provide for
another of my unusual use cases.

Take care,
-Thomas

**Comment by dagraham** [comment]
Thomas,

3.2.10 has the @n feature for ‘-‘ and ‘%’ tasks. Possible values include d, k and t - see the user manual section under @keys for the details. You will note that I shamelessly stole your “poor man’s cron” and used it there.

The topic of visiting colleges sure brings back memories - all good. I hope yours are as well.

-Dan


On Aug 20, 2015, at 10:00 PM, therden <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Dan,

Sorry for the delayed response; I was occupied all day taking one of my
kids to visit a college campus a few hours away.

Your proposed new @n attribute sounds like it'll work great for my purpose
of using etm as a kind of "poor man's cron."

Thank you very much for taking the time to think about how to provide for
another of my unusual use cases.

Take care,
-Thomas

**Comment by therden** [comment]
Thank you for the kind words, Dan -- yesterday's was a successful campus
visit -- and thanks again for developing the @n attribute.

I'm pleased you liked the phrase well enough to re-use it.

I won't get a chance to do so during the workday today, but will check out
the latest ETM version over the weekend so that I can send you an *informed*
thumbs up afterward.

Take care,
-Thomas

**Comment by therden** [comment]
@n attribute's working great; thank you again.

Enjoy the start of the new semester...
-Thomas

**Comment by dagraham** [comment]
I’m glad to hear it. Thanks

On Aug 24, 2015, at 9:34 AM, therden <notifications@github.com<mailto:notifications@github.com>> wrote:


@n<https://github.com/n> attribute's working great; thank you again.

Enjoy the start of the new semester...
-Thomas
