### ISSUE TITLE
Certain keybindings not working in Version 3.2.7 

### ISSUE THREAD

**Issue by therden** [dagraham/etm-tk#44]
Ctrl-W is not saving items opened for Editing.

**Comment by dagraham** [comment]
That’s right - the binding was changed to Ctrl-S as noted in Shortcuts (bound to ?). The Ctrl-W binding was causing conflicts on my mac.

On Aug 19, 2015, at 5:01 PM, therden <notifications@github.com<mailto:notifications@github.com>> wrote:


Ctrl-W is not saving items opened for Editing.

**Comment by therden** [comment]
lI see.  If that was mentioned in a Groups thread I must have missed it.

This change will make etm more consistent with with many/most other
applications, which (as soon as I erase my muscle memory of the Ctrl-W
combination!) will be all to the good.

-Thomas
