### ISSUE TITLE
Can actions be shown in agenda view

### ISSUE THREAD

**Issue by lawquest** [dagraham/etm-tk#45]
I would like to spend more time in agenda view,  but I have to go to weekly view to see the day's actions.   Alternatively, in the weekly view, where I now spend most of my time,  the data now available under Next-None in the agenda view is not available.

Any shot that agenda view could show actions or that weekly view could show Next-None?

No big deal but I think it would save some time.

**Comment by dagraham** [comment]
3.2.16 will add 'agenda_omit' to options:

    agenda_omit: [ac, fn, ns]

Items in agenda_omit will not be displayed in the agenda day list. Possible choices include: ac: actions, by: begin by warnings, fn: finished tasks, ns: notes (dated) and oc: occasions.
