### ISSUE TITLE
switching from agenda to weekly or monthly view with cap lock on

### ISSUE THREAD

**Issue by lawquest** [dagraham/etm-tk#46]
When switching from aganda to Weekly view with cap lock on, nothing happens.
When switching from agenda to Monthly view with cap lock on, following error shows:
  "A configuration setting for 'ics_subscriptions' is required but missing."

At this time my ics_subscriptions in etmtk.cfg is intentionally blank as I don't export to any other calendar, though I might change this as staff, sadly, still uses google calendar.

I don't think this switching view situation is a problem as one quickly learns to make sure cap locks is off when switching views.  I just thought I would point it out in case you wanted to change the error message to "cap locks on" or some such.

**Comment by dagraham** [comment]
Shift-M is bound to "update calendar subscriptions".

On Sep 17, 2015, at 11:07 PM, lawquest <notifications@github.com<mailto:notifications@github.com>> wrote:


When switching from aganda to Weekly view with cap lock on, nothing happens.
When switching from agenda to Monthly view with cap lock on, following error shows:
"A configuration setting for 'ics_subscriptions' is required but missing."

At this time my ics_subscriptions in etmtk.cfg is intentionally blank as I don't export to any other calendar, though I might change this as staff, sadly, still uses google calendar.

I don't think this switching view situation is a problem as one quickly learns to make sure cap locks is off when switching views. I just thought I would point it out in case you wanted to change the error message to "cap locks on" or some such.
