### ISSUE TITLE
can't install 3.2.18

### ISSUE THREAD

**Issue by lawquest** [dagraham/etm-tk#50]
3.2.16 installs fine, I am having trouble installing 3.2.16.

On running 
root@debian:/home/johwhi/src/etmtk/etmtk-3.2.18# python setup.py install,

I get the following error:

Installed /usr/local/lib/python2.7/dist-packages/etmtk-3.2.18-py2.7.egg
Processing dependencies for etmtk==3.2.18
Searching for python>=2.7.6,<3.0
Reading https://pypi.python.org/simple/python/
Reading http://www.python.org
Reading http://www.python.org/2.3
Reading http://www.python.org/2.4
Reading http://www.python.org/2.4.1
Reading http://www.python.org/2.5
Reading http://www.python.org/download/
No local packages or download links found for python>=2.7.6,<3.0
error: Could not find suitable distribution for Requirement.parse('python>=2.7.6,<3.0')

root@debian:/home/johwhi/src/etmtk/etmtk-3.2.18# 

I have python 2.7.9-2

John

**Comment by dagraham** [comment]
John,

Would you open the file named “setup.py” in 3.2.18 in your editor and change the lines:

if sys.version_info >= (3, 2):
    REQUIRES = ["python-dateutil>=1.5", "PyYaml>=3.10"]
else:
    REQUIRES = ["python>=2.7.6,<3.0", "python-dateutil>=1.5", "PyYaml>=3.10”]

to the single line

REQUIRES = ["python-dateutil>=1.5", "PyYaml>=3.10"]

and let me know if this fixed the problem for you?

Thanks,
Dan

On Oct 21, 2015, at 8:43 PM, lawquest <notifications@github.com<mailto:notifications@github.com>> wrote:


3.2.16 installs fine, I am having trouble installing 3.2.16.

On running
root@debian:/home/johwhi/src/etmtk/etmtk-3.2.18# python setup.py install,

I get the following error:

Installed /usr/local/lib/python2.7/dist-packages/etmtk-3.2.18-py2.7.egg
Processing dependencies for etmtk==3.2.18
Searching for python>=2.7.6,<3.0
Reading https://pypi.python.org/simple/python/
Reading http://www.python.org
Reading http://www.python.org/2.3
Reading http://www.python.org/2.4
Reading http://www.python.org/2.4.1
Reading http://www.python.org/2.5
Reading http://www.python.org/download/
No local packages or download links found for python>=2.7.6,<3.0
error: Could not find suitable distribution for Requirement.parse('python>=2.7.6,<3.0')

root@debian:/home/johwhi/src/etmtk/etmtk-3.2.18#

I have python 2.7.9-2

John

**Comment by lawquest** [comment]
Yes.  That fixed the problem for me.

Thanks.

John
