### ISSUE TITLE
Editing repeating task, with completed and rescheduled past ooccurences, fails with error message

### ISSUE THREAD

**Issue by stef204** [dagraham/etm-tk#52]
* Create repeating task, e.g. daily

"- DO XYZ @s 2015-08-20 5pm @a 0m: m 
@r d &w MO, TU, WE, TH, FR &u 2015-12-16 
 @t some_tag"

* On a daily basis, mark task as completed using "Finish" and entering "now" as value.

* as days pass, occasionally reschedule single occurences, e.g. on any given (random) day of the week, reschedule task from 5m to 6pm, continuing to mark it as finished|now each time.

* Once a few occurrences of task have been rescheduled and marked as "finished" (thus task now contains many occurrences of @+ @- and @f) use: Edit|All Instances to change time from 5pm to 6pm--no other changes are made or desired--for repeating task.

Error message:

> 09/02/15 05:00PM  is listed in @- but doesn't match any datetimes generated by @r.
09/03/15 05:00PM  is listed in @- but doesn't match any datetimes generated by @r.
09/07/15 05:00PM  is listed in @- but doesn't match any datetimes generated by @r.
09/11/15 05:00PM  is listed in @- but doesn't match any datetimes generated by @r.
09/25/15 05:00PM  is listed in @- but doesn't match any datetimes generated by @r.
10/05/15 05:00PM  is listed in @- but doesn't match any datetimes generated by @r.
10/07/15 05:00PM  is listed in @- but doesn't match any datetimes generated by @r.
10/12/15 05:00PM  is listed in @- but doesn't match any datetimes generated by @r.
10/13/15 05:00PM  is listed in @- but doesn't match any datetimes generated by @r.
10/14/15 05:00PM  is listed in @- but doesn't match any datetimes generated by @r.
10/20/15 05:00PM  is listed in @- but doesn't match any datetimes generated by @r.
10/21/15 05:00PM  is listed in @- but doesn't match any datetimes generated by @r.
10/22/15 05:00PM  is listed in @- but doesn't match any datetimes generated by @r.
10/27/15 05:00PM  is listed in @- but doesn't match any datetimes generated by @r.
10/28/15 05:00PM  is listed in @- but doesn't match any datetimes generated by @r.
10/29/15 05:00PM  is listed in @- but doesn't match any datetimes generated by @r.
10/30/15 05:00PM  is listed in @- but doesn't match any datetimes generated by @r.

* Here is full text of task XYZ

> "- DO XYZ @s 2015-08-18 5pm @a 0m: m 
  @t some_tag
  @f 20150818T1759;20150818T1700, 
  20150819T1838;20150819T1700, 
  20150820T1730;20150820T1700, 
  20150821T1754;20150821T1700, 
  20150824T1656;20150824T1700, 
  20150825T1958;20150825T1700, 
  20150826T1823;20150826T1700, 
  20150827T1843;20150827T1700, 
  20150901T1900;20150901T1700, 
  20150902T2050;20150902T1830, 
  20150903T1940;20150903T1930, 
  20150908T1549;20150908T1700, 
  20150909T1926;20150909T1700, 
  20150914T2125;20150914T1700, 
  20150915T1754;20150915T1700, 
  20150917T1804;20150917T1700, 
  20150921T1831;20150921T1700, 
  20150922T1941;20150922T1700, 
  20150923T1741;20150923T1700, 
  20150928T1830;20150928T1700, 
  20150930T1731;20150930T1700, 
  20151001T1927;20151001T1700, 
  20151002T1615;20151002T1700, 
  20151006T1751;20151006T1700, 
  20151008T1810;20151008T1700, 
  20151009T1926;20151009T1700, 
  20151015T1600;20151015T1700, 
  20151016T1600;20151016T1700, 
  20151019T1924;20151019T1700, 
  20151023T1720;20151023T1700, 
  20151026T1503;20151026T1700, 
  20151102T1950;20151102T1700 
  @r d &w MO, TU, WE, TH, FR &u 2015-12-15 
  @+ 20150902T1830, 20150903T1930, 20150911T2345 
  @- 20150902T1700, 20150903T1700, 20150907T1700, 20150911T1700, 20150925T1700, 20151005T1700, 20151007T1700, 20151012T1700, 20151013T1700, 20151014T1700, 20151020T1700, 20151021T1700, 20151022T1700, 20151027T1700, 20151028T1700, 20151029T1700, 20151030T1700 @o s 
  @z sometimezone"

* If INSTEAD try to use, "Edit|This and all subsequent instances", nothing happens, no dialog box for editing.

**Comment by dagraham** [comment]
All the completed instances show the "due" time as 5pm, e.g., 20150818T1759;20150818T1700. When you edit ALL INSTANCES and change the due time to 6pm, you render all the prior completions and prior @- entries inconsistent and thus get the warnings. The easy solution is not to change all instances but only THIS AND ALL SUBSEQUENT INSTANCES for some repetition beyond your last completion or @- entry. That way you're not trying to revise history.

**Comment by stef204** [comment]
Agreed BUT you missed the **last** bullet point of my original post:

* If INSTEAD try to use, "Edit|This and all subsequent instances", nothing happens, no dialog box for editing.

This means nothing happens whatsoever--I am NOT presented with a dialog box to "Edit|This and all subsequent instances".  So I am unable to edit the task.  I could possibly go into the config file to edit that, but it would be most inconvenient and prone to errors.

Can you please look into this?

**Comment by dagraham** [comment]
I missed your second bullet - didn’t scroll down far enough.

This is not the behavior I get under either OSX or Ubuntu where the “this and subsequent” choice opens the editor as it should. What is your platform? Is there any console output? Does this problem occur whenever you choose “this and subsequent” for other repeating items?

-Dan

On Nov 6, 2015, at 6:39 AM, stef204 <notifications@github.com<mailto:notifications@github.com>> wrote:


Agreed BUT you missed the last bullet point of my original post:

  *   If INSTEAD try to use, "Edit|This and all subsequent instances", nothing happens, no dialog box for editing.

This means nothing happens whatsoever--I am NOT presented with a dialog box to "Edit|This and all subsequent instances". So I am unable to edit the task. I could possibly go into the config file to edit that, but it would be most inconvenient and prone to errors.

Can you please look into this?

**Comment by stef204** [comment]
Yes, it happens for what seems to be ALL repeating items.

Platform: Linux 4.2.5 x86_64 GNU/Linux
Python: 3.5.0

Console output:

> % etm
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1549, in __call__
    return self.func(*args)
  File "/usr/lib/python3.5/site-packages/etmTk/view.py", line 1077, in <lambda>
    self.tree.bind(c, lambda e: self.after(AFTER, cmd(e)))
  File "/usr/lib/python3.5/site-packages/etmTk/view.py", line 1768, in editItem
    if tmp_copy:
NameError: name 'tmp_copy' is not defined

Let me know any specific debug steps you need me to do, and I would be glad to provide the info. Thanks.

**Comment by dagraham** [comment]
Would you open "/usr/lib/python3.5/site-packages/etmTk/view.py" in your editor, change line 1768 from


if tmp_copy:

to

if tmp_cpy:

and let me know if this change fixes the problem?

Thanks,
Dan

On Nov 6, 2015, at 8:30 AM, stef204 <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, it happens for what seems to be ALL repeating items.

Platform: Linux 4.2.5 x86_64 GNU/Linux
Python: 3.5.0

Console output:

% etm
Exception in Tkinter callback
Traceback (most recent call last):
File "/usr/lib/python3.5/tkinter/init.py", line 1549, in call
return self.func(*args)
File "/usr/lib/python3.5/site-packages/etmTk/view.py", line 1077, in
self.tree.bind(c, lambda e: self.after(AFTER, cmd(e)))
File "/usr/lib/python3.5/site-packages/etmTk/view.py", line 1768, in editItem
if tmp_copy:
NameError: name 'tmp_copy' is not defined

Let me know any specific debug steps you need me to do, and I would be glad to provide the info. Thanks.

**Comment by dagraham** [comment]
I've changed the snooze behavior and made the tmp_cpy correction in the repository. If these changes fix the issues you raised would you  please close the relevant issues? 
Thanks,
Dan

**Comment by stef204** [comment]
Issue is fixed, thank you.
