### ISSUE TITLE
typo in ETM users manual

### ISSUE THREAD

**Issue by lawquest** [dagraham/etm-tk#55]
In "Item Types" on the first page (index), there is no dash ("-")  before Tasks, i.e. it should read "-Tasks" rather than just "Tasks."

**Comment by dagraham** [comment]
There are 3 types of tasks with type characters -, % and +.  There are subsections under "Tasks" for each of the 3 types and the relevant type character appears in the heading for each of these subsections. I've changed the overall heading to "-, % and + Tasks".

**Comment by lawquest** [comment]
Obviously I have got to spend more time learning tasks.  I am using custom views now a lot.  If I want to just look at the billing or hours logged for a particular client, its great.  My next major step is going to be to start to use the conditional tasks.  For example, our probate form book has a 3 or 4 page checklist.  I hope to someday get to the point where I can drop it in to etm.  The date (or need) for the next step is never known at the outset.  All that is known is that once the person dies (and becomes a decedent) time deadlines go into place.  Then if will is admitted to probate, new time deadlines become relevant. Some depend on whether decedent had a will or not.  If property is to be sold during probate, more deadlines arrive.  I believe this kind of thing is right up etm's alley, but haven't used that capability.  I am attaching the checklist to give you a better idea of what I am talking about.
John
[2016-01-12-probate-timeline-checklist.PDF](https://github.com/dagraham/etm-tk/files/96591/2016-01-12-probate-timeline-checklist.PDF)
