### ISSUE TITLE
catching bad alert command

### ISSUE THREAD

**Issue by melnospam** [dagraham/etm-tk#56]
In my "etmtk.cfg" I forgot to put !time_span! inside quotes.
This wasn't a problem until recently (the last upgrade to 3.2.23?)
when I noticed I was getting lines like,
        "/bin/sh: 1: Syntax error: "(" unexpected"
in the terminal where etmtk was started.
It appears !time_span! now gets expanded to something like,
        6:06pm Mon Jan 25 (Today)
Was the "(Today)" added recently?
It took me a while to figure out the error was coming from
"etm" since I have other programs started in the same terminal.
When I added a print in etmTk/view.py to see what it was
doing it was obvious I needed "!time_span!".  

Anyway my suggestion is would it possible to check the return
value of the calls to subprocess.call() and print an error
message showing what etm command failed?  My problem is solved
but I can imagine for example having some character sequence
in "!summary!" that would cause a problem even if it's in quotes.

**Comment by dagraham** [comment]
Thanks Mel. This is fixed, I hope, on github. Pending your approval, I'll release a new version on PyPI.

**Comment by melnospam** [comment]
I download the latest from git and I'm getting:
    Exception in Tkinter callback
    Traceback (most recent call last):
      File "/home/jaym/local/python3/lib/python3.5/tkinter/__init__.py", line 1549, in __call__
        return self.func(*args)
      File "/home/jaym/local/python3/lib/python3.5/tkinter/__init__.py", line 596, in callit
        func(*args)
      File "/home/jaym/python/etmtk/etm-tk-master/etmTk/view.py", line 3647, in updateClock
        self.updateAlerts()
      File "/home/jaym/python/etmtk/etm-tk-master/etmTk/view.py", line 3719, in updateAlerts
        self.check_output(dcmd.encode(loop.options['encoding']['gui']))
      File "/home/jaym/python/etmtk/etm-tk-master/etmTk/view.py", line 3674, in check_output
        output = subprocess.check_output(cmd, stderr=STDOUT, shell=True)
NameError: name 'STDOUT' is not defined

The error output I get is:

    /bin/sh: 1: Syntax error: "(" unexpected
    b''
    --- 2016-02-03 14:59:00,021 - ERROR - view.check_output
        check_output: b''

That's better but could it include the command that failed?

**Comment by dagraham** [comment]
Mel,

Sorry, "stderr=STDOUT" should instead be "stderr=subprocess.STDOUT". 
Somehow this last bit wasn't included in the earlier github sync but is now.

-Dan

melnospam wrote:
>
> output = subprocess.check_output(cmd, stderr=STDOUT, shell=True)
> NameError: name 'STDOUT' is not defined
>

**Comment by melnospam** [comment]
OK, but still I think it would be nice to include the cmd that
failed in the error output to the terminal and logger.error.
For example something like:
    print("ERROR[etm subprocess]: %s" % cmd)
    logger.error("check_output: {0}\nfor: {1}".format(exc.output, cmd))

**Comment by dagraham** [comment]
Good idea - I'll do it tomorrow.

-Dan

**Comment by dagraham** [comment]
p4 includes the cmd as you suggested. Please close this if you are OK with it.  Thanks very much for your help.

**Comment by melnospam** [comment]
"p4" looks good.  I will close this issue after this comment.
As always, thanks for all you do.
