### ISSUE TITLE
Repeating item's @f key and values mistakenly included when editing "1: this instance"

### ISSUE THREAD

**Issue by therden** [dagraham/etm-tk#57]
When an attempt is made to edit a repeating item and the option "**1: this instance**" is chosen, the text loaded into the editor *includes* the repeating item's ***@f*** key and values.  

In this circumstance, the ***@f*** key and its associated values should be *excluded*, just as they are when the option "**2: this and all subsequent instances**" is chosen.

**Comment by dagraham** [comment]
This should be fixed in 3.2.25. Please check it out when you have time and mark this closed if it is ok. Thanks.

**Comment by therden** [comment]
Yes, it is fixed -- thank you, Dan.
