### ISSUE TITLE
No support for creating '=' (default values) items

### ISSUE THREAD

**Issue by therden** [dagraham/etm-tk#59]
Has **ETM** *already* dropped support for '=' default values?

Just noticed this afternoon that when I open a new item within **ETM** and start it with a '= ', the *Creating a New Item* dialog won't let me save the item.

**Comment by dagraham** [comment]
There has been no change in the treatment of "=" items and I can't duplicate this problem. Do you get any error messages?

**Comment by therden** [comment]
Nope.  

If I edit a file outside of **ETM** and add a "=" item to a data file, the application appears to process the item as per usual.  

But if I open a new item *within* **ETM** and enter, for instance, the User Manual example `= @k client_1:project_a`, then when I press the 'Save and Close' button nothing happens.  No error message comes up, and the 'creating a new item' dialog remains open and unsaved.

**Comment by dagraham** [comment]
This should be fixed in the latest github version. When you have time, would you please check it out and close this issue if it's ok? Thanks.

**Comment by therden** [comment]
That's done it; Thank you.
